### ISSUE TITLE
Enable (Optional) User Property Validation

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#143]
### This issue relates to a:

- [ ] Bug
- [ ] Suggestion
- [x] Feature Proposal

### Description:

Something we can enable is property validation on User creates and updates. What this will include is:

- Allow user to specify if they want property validation in the config file.
- If they want validation, they also have to list the property names and types in the config file.
- On a User create/update, Thunder will validate that the User object coming in the `POST` or `PUT` has the same number of properties as listed in the config, as well as they have the same property names and the value is the correct type.

This would be a huge feature that would allow users of Thunder to be more confident that the data they are creating in the database looks consistent. It will be optional in case some users want the flexibility to put any number of properties in the User object.

### Additional Information:

The config section may look like:

```yaml
propertyValidation: true
properties:
  - name: myFirstProperty
    type: string
  - name: mySecondProperty
    type: list
```
