### ISSUE TITLE
Use correct logic with custom URL placeholder

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#162]
### This issue relates to a:

- [ ] Bug
- [ ] Suggestion
- [x] Feature Proposal

### Description:

Continuation of #150. The user should be able to (optionally) customize the string that is used as a placeholder for the URL. Here are the following scenarios and what should happen:

1. **No `urlPlaceholderString` defined and no custom email pages defined**

    Use the default `CODEGEN-URL` and the default HTML/Text files

2. **Custom `urlPlaceholderString` (not equal to `CODEGEN-URL`) and no custom email pages**

    Log warning and use `CODEGEN-URL` anyway with the default files

3. **No `urlPlaceholderString` defined and one or both custom email pages defined**

    Use default `CODEGEN-URL` and the custom pages or one custom page and one default

4. **Custom `urlPlaceholderString` (not equal to `CODEGEN-URL`) and one custom email page**

    Use the custom placeholder for the one page that is custom, use `CODEGEN-URL` for the other

5. **Custom `urlPlaceholderString` (not equal to `CODEGEN-URL`) and both custom email pages**

    Use the custom placeholder for both custom pages

**Comment by RohanNagar** [comment]
Also want to customize email subject. Want to start using a `EmailMessage` class with a builder pattern. Also want a separate configuration object within `ses` for message options, and want configuration to look like:

```yaml
ses:
  endpoint:
  region:
  fromAddress:
  messageOptions:
    subject:
    bodyHtmlFile:
    bodyTextFile:
    urlPlaceholderString:
    successHtmlFile:
```
