### ISSUE TITLE
Restructure Integration Tests for Multiple Configurations

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#225]
**Description**

I want the integration tests to look like:

- A YAML file is used to define all of the tests for a given Thunder configuration
- The test runner reads the file and runs all of the tests
- The tests check for matching status codes and responses
- Multiple files can be used - one for each possible Thunder configuration that we want to test

Also:
- With multiple ways to run Thunder locally (jar, `docker-compose`), as well as dependencies locally (npm run, `start-local-dependencies.js`, `docker-compose`), I want to document and clean up these options so that it is easier to develop
- Would be a bonus if we can converge the CI builds into Travis, so Travis also runs the docker builds. We can take advantage of build stages to run multiple integration tests against the docker images

**Additional context**

Example of test config:

**This is outdated. Current format is in the PR**

```yaml
tests:
  create:
    - log: 'Checking for 400 when creating a null user...'
      name: 'CREATE NULL USER'
      body: null
      expectedCode: 400
      expectedResponse: 'Cannot post a null user.'
    - log: 'Checking for 400 when creating a user with a null email...'
      name: 'CREATE NULL EMAIL'
      body:
        email:
          address: null
        password: 'test'
        properties:
      expectedCode: 400
      expectedResponse: 'Cannot post a user with a null email.'
```
