### ISSUE TITLE
Support More Complex Hashing Schemes

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#258]
**Describe the problem that this feature would solve**

Right now, Thunder does no hashing/hash comparison for passwords. It simply reads the password in the header and does a direct String comparison to the password stored in the database. This works fine for a simple hash, but not for more complex types that add a salt.

For example, bcrypt can generate different hashes for the same string, but those hashes should be treated as equal. If you use bcrypt or other similar hash functions in the client-side today, Thunder will not be able to match up the passwords.

**Describe the solution you'd like**

Thunder should, through a configuration option, be able to handle specific hash implementations. For example, we can have a configuration option like this:

```yaml
passwordHash:
  algorithm: [simple|bcrypt|md5|none] # Default to simple (defines the algorithm to use in the below settings)
  serverSideHash: [true|false] # Default to false for v2.x, v3.x default to true (whether or not to hash the password for a new user/updated user if the password changed)
  headerCheck: [true|false] # Default to true (whether or not to check the password header (coming in as plaintext) for match
```
We can initially support `simple` (which is a direct String comparison) and will be the default. We can also initially support `bcrypt` and `scrypt`, some of the more popular ones today.

**Additional context**

https://www.stubbornjava.com/posts/hashing-passwords-in-java-with-bcrypt
