### ISSUE TITLE
Migrate from Travis CI to Github CI

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#778]
**Description**

```yaml
name: Java CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install npm packages
      run: npm --prefix scripts/ install
    - name: Lint Node.js code
      run: npm --prefix scripts/ run lint
    - name: Shellcheck
      run: shellcheck scripts/**/*.sh
    
  build:
    runs-on: ubuntu-latest
    
    env:
      # Dummy keys to use the AWS SDK
      AWS_ACCESS_KEY_ID: 1234567890
      AWS_SECRET_ACCESS_KEY: 1234567890

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install npm packages
      run: npm --prefix scripts/ install

    - name: Build with Maven
      run: mvn package jacoco:report

    - name: Run itegration tests
      run: sh -c scripts/tools/integration-tests.sh

    - name: Docker compose integration test
      run: ./scripts/ci/docker-integration-tests.sh general
```

https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts

**Additional context**
